/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_JNITest */

#ifndef _Included_com_example_ndk_JNITest
#define _Included_com_example_ndk_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_JNITest
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndk_JNITest_getStringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    javaStringToCString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_javaStringToCString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    javaArrayCopyToCArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_javaArrayCopyToCArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    cArrayCopyToJavaArray
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ndk_JNITest_cArrayCopyToJavaArray
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    javaField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_javaField
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    callMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_callMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    accessExceptionMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_accessExceptionMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_JNITest
 * Method:    throwExceptionMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_JNITest_throwExceptionMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
